### ISSUE TITLE
Unable to build native image after upgrading from 0.3 to 2.1.0

### ISSUE THREAD

**Issue by argo1089** [quarkiverse/quarkus-lucene#140]
Error: Could not find target method: private static java.lang.Object org.apache.lucene.store.MMapDirectoryReplacementJDK.unmapHackImpl()

**Comment by dainiusjocas** [comment]
The class is still there https://github.com/quarkiverse/quarkus-lucene/blob/main/runtime/src/main/java/org/apache/lucene/store/MMapDirectoryReplacementJDK.java 

Could you show your setup? Which GraalVM you're using? Which Java version? How do you generate reflection hints?

**Comment by argo1089** [comment]
This is when building a native linux executable inside a container environment.

Image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
Project java version: 11
Quarkus version: 3.1.2.Final
Lucene version: 2.1.0 (build completes without errors when this is downgraded to version 0.3)

**Comment by wglanzer** [comment]
Hi there! I got the same error, and I'm using GraalVM-CE-17.
You mentioned "reflection hints" - what do I have to register in order to make your extension work in native images?
I tried it by registering the replacement class in a `reflection-config.json`:
```
[
  {
    "name" : "org.apache.lucene.store.MMapDirectoryReplacementJDK",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

I added the property `<quarkus.native.additional-build-args>-H:ReflectionConfigurationFiles=reflection-config.json</quarkus.native.additional-build-args>` to my maven build pipeline too, of course.

Do you know what I am missing here?

**Comment by dainiusjocas** [comment]
I've tested that PR made by @wglanzer fixes the issue.
